import SideBar from "@/components/SideBar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full h-full flex md:grid md:grid-cols-6 lg:grid-cols-4">
          {/* SideBar */}
          <SideBar />

          {/* Feed */}
          <div className="flex-grow md:col-span-3 lg:col-span-2">
            {children}
          </div>

          {/* Widgets */}
          <div className="hidden md:flex">Feed</div>
        </div>
      </body>
    </html>
  );
}
